# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Breakpoint' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Breakpoint
  # add pods for desired Firebase product
  # https://firebase.google.com/docs/ios/setup#available-pods
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Auth'
end
